import { tArmor } from '../../type'
import {
  ADVENTURER_BOOTS,
  ADVENTURER_CLOAK,
  ADVENTURER_HOOD,
} from './adventure'
import {
  ANTIQUATED_ATTIRE,
  ANTIQUATED_HAT,
  ANTIQUATED_SHOES,
} from './antiquated'
import { APPRENTICE_CAP, APPRENTICE_ROBE, APPRENTICE_SHOES } from './apprentice'
import {
  ARISTOCRAT_ATTIRE,
  ARISTOCRAT_HAT,
  ARISTOCRAT_SHOES,
} from './aristocrat'
import { BONE_ARMOR, BONE_BOOTS, BONE_HELMET } from './bone'
import {
  EXECUTIONER_ARMOR,
  EXECUTIONER_BOOTS,
  EXECUTIONER_HELMET,
} from './executioner'
import {
  GRAVEGUARD_ARMOR,
  GRAVEGUARD_BOOTS,
  GRAVEGUARD_HELMET,
} from './graveguard'
import { HUNTER_BOOTS, HUNTER_CLOAK, HUNTER_HOOD } from './hunter'
import { IRON_ARMOR, IRON_BOOTS, IRON_HELMET } from './iron'
import { NOVICE_HAT, NOVICE_ROBES, NOVICE_SHOES } from './novice'
import { PATRICIAN_ATTIRE, PATRICIAN_HAT, PATRICIAN_SHOES } from './patrician'
import { RANGER_BOOTS, RANGER_CLOAK, RANGER_HOOD } from './ranger'
import { STUDENT_BOOTS, STUDENT_CAP, STUDENT_ROBES } from './student'
import { TOMB_ARMOR, TOMB_BOOTS, TOMB_HELMET } from './tomb'

export const ARMOR_BY_LEVEL: Record<number, (() => tArmor)[]> = {
  0: [
    RANGER_HOOD,
    RANGER_CLOAK,
    RANGER_BOOTS,
    PATRICIAN_HAT,
    PATRICIAN_ATTIRE,
    PATRICIAN_SHOES,
    EXECUTIONER_HELMET,
    EXECUTIONER_ARMOR,
    EXECUTIONER_BOOTS,
    STUDENT_CAP,
    STUDENT_ROBES,
    STUDENT_BOOTS,
    TOMB_HELMET,
    TOMB_ARMOR,
    TOMB_BOOTS,
  ],
  1: [
    ADVENTURER_HOOD,
    ADVENTURER_CLOAK,
    ADVENTURER_BOOTS,
    ARISTOCRAT_HAT,
    ARISTOCRAT_ATTIRE,
    ARISTOCRAT_SHOES,
    GRAVEGUARD_HELMET,
    GRAVEGUARD_ARMOR,
    GRAVEGUARD_BOOTS,
    APPRENTICE_CAP,
    APPRENTICE_ROBE,
    APPRENTICE_SHOES,
  ],
  2: [
    HUNTER_HOOD,
    HUNTER_CLOAK,
    HUNTER_BOOTS,
    ANTIQUATED_HAT,
    ANTIQUATED_ATTIRE,
    ANTIQUATED_SHOES,
    IRON_HELMET,
    IRON_ARMOR,
    IRON_BOOTS,
    BONE_HELMET,
    BONE_ARMOR,
    BONE_BOOTS,
    NOVICE_HAT,
    NOVICE_ROBES,
    NOVICE_SHOES,
  ],
}
